{{- if .Values.settingsToml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rusty-valkey-forward-auth.fullname" . }}-settings
  labels:
    {{- include "rusty-valkey-forward-auth.labels" . | nindent 4 }}
data:
  settings.toml: |-
    {{- tpl .Values.settingsToml . | nindent 4 }}
{{- end }}
