apiVersion: v2
name: rusty-valkey-forward-auth
description: Helm chart for deploying the Rusty Valkey Forward Auth service.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - valkey
  - oauth2
  - forward-auth
  - rust
dependencies:
  - name: valkey
    version: 0.7.7
    repository: https://valkey.io/valkey-helm/
